version: "3.9"
services:
    backend:
        image: taburett-tichu
        container_name: tichu-boot
        build:
            context: ./tjchu
        ports:
            - "8080:8080"
    frontend:
        image: ngtichu
        container_name: ngtichu
        build:
            context: ./ngtichu
        ports:
            - "4200:80"
        depends_on:
            - backend


